
const imageFilenames = [
    "NewGirls/Girl1.webp",
    "NewGirls/Girl2.webp",
    "NewGirls/Girl3.webp",
    "NewGirls/Girl4.webp",
    "NewGirls/Girl5.webp",
    "NewGirls/Girl6.webp",
    "NewGirls/Girl7.webp",
    "NewGirls/Girl8.webp",
    "NewGirls/Girl9.webp",
    "NewGirls/Girl10.webp",
    "NewGirls/Girl11.webp",
    "NewGirls/Girl12.webp",
    "NewGirls/Girl13.webp",
    "NewGirls/Girl14.webp",
    "NewGirls/Girl15.webp",
    "NewGirls/Girl16.webp",
    "NewGirls/Girl17.webp",
    "NewGirls/Girl18.webp",
    "NewGirls/Girl19.webp",
    "NewGirls/Girl20.webp",
    "NewGirls/Girl21.webp",
    "NewGirls/Girl22.webp",
    "NewGirls/Girl23.webp",
    "NewGirls/Girl24.webp",
    "NewGirls/Girl25.webp",
];
